### ISSUE TITLE
Changes on the robot

### ISSUE THREAD

**Issue by jmirabel** [agimus/agimus-vision#2]
@ksyy On the robot, in `src/tracker_object/detector.cpp`, there is something which I did not understand:
```
         vpPixelMeterConversion::convertPointWithoutDistortion( _cam_parameters, _image_points[ i ], x, y );
+        //vpPixelMeterConversion::convertPointWithDistortion( _cam_parameters, _image_points[ i ], x, y );
```

Do we agree that we should use `convertPointWithoutDistortion` if we use topic `rgbd/rbg/high_res/image_rect` ?

**Comment by ksyy** [comment]
Yes, I do agree, we need to use `convertPointWithoutDistortion` with the topic `image_rect`.

But I tried to use `image_raw` at one time and obviously took the conversion function with the distortion model, and somehow forgot to remove that from the commit…

**Comment by jmirabel** [comment]
Thanks for the explanation.
